### ISSUE TITLE
How is this used in GDScript?

### ISSUE THREAD

**Issue by SlimyFrog123** [drwhut/open_tabletop_import_module#2]
Sorry if this is a dumb question, but how do I use this in GDScript?

I built the engine with this module and instanced a TabletopImporter, but I can't figure out how to import and instance a model from the disk.

I tried looking in the source code from Tabletop Club, but I still couldn't figure it out from there.

Thanks in advance!

**Comment by drwhut** [comment]
Once you have a `TabletopImporter`, you can call the `import` function to import a 3D model in the following way:

```
importer.import("path/to/model.glb", "path/to/arbitrary/dir/file_name", {})
```

As an example, currently in the `0.2-rewrite` branch of the game, the call looks something like this, if the file name is for example "cube.glb":
```
importer.import("/home/drwhut/cube.glb", "user://.import/cube", {})
```

The first argument is the file you are importing, and the second argument is the basename (i.e. without the extension, because it can change depending on what you are importing) of where Godot stores the actual imported files which it can read.

NOTE: This will create a `.import` file next to your model, so Godot knows where to look for the generated files.

You can then use GDScript's `load` function to instance the model within the game at run-time:
```
var my_cube = load("/home/drwhut/cube.glb")
```

**Comment by SlimyFrog123** [comment]
> Once you have a `TabletopImporter`, you can call the `import` function to import a 3D model in the following way:
> 
> ```
> importer.import("path/to/model.glb", "path/to/arbitrary/dir/file_name", {})
> ```
> 
> As an example, currently in the `0.2-rewrite` branch of the game, the call looks something like this, if the file name is for example "cube.glb":
> 
> ```
> importer.import("/home/drwhut/cube.glb", "user://.import/cube", {})
> ```
> 
> The first argument is the file you are importing, and the second argument is the basename (i.e. without the extension, because it can change depending on what you are importing) of where Godot stores the actual imported files which it can read.
> 
> NOTE: This will create a `.import` file next to your model, so Godot knows where to look for the generated files.
> 
> You can then use GDScript's `load` function to instance the model within the game at run-time:
> 
> ```
> var my_cube = load("/home/drwhut/cube.glb")
> ```

This is my code:
```
var import_path: String = ProjectSettings.globalize_path(IMPORT_PATH + path.get_file())

print("Importing: ", path, " to: ", import_path)

var result = importer.import(path, import_path, {})

print(result)

if result == OK:
	print("Loading model...")
	var node = load(path)
```

It doesn't seem to be getting past the import function. The program crashes. This is what the log says:
```
Godot Engine v3.5.3.stable.custom_build.6c814135b - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2
Async. shader compilation: OFF
 
Importing: C:/Users/DJ Cook/Downloads/low-poly_fn_scar_h.glb to: C:/Users/DJ Cook/AppData/Roaming/Godot/app_userdata/Survival Game Tools/.imports/low-poly_fn_scar_h.glb

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v3.5.3.stable.custom_build (6c814135b69d4e703956bacc2073b4b179ff5a00)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] EditorNode::progress_add_task (D:\Godot Engine\godot\editor\editor_node.cpp:4154)
[1] EditorProgress::EditorProgress (D:\Godot Engine\godot\editor\editor_node.h:905)
[2] ResourceImporterScene::import (D:\Godot Engine\godot\editor\import\resource_importer_scene.cpp:1226)
[3] TabletopImporter::import (D:\Godot Engine\godot\modules\tabletop_club_godot_module\tabletop_importer.cpp:153)
[4] MethodBind3R<TabletopImporter,enum Error,String const &,String const &,Dictionary const &>::call (D:\Godot Engine\godot\core\method_bind.gen.inc:2551)
[5] Object::call (D:\Godot Engine\godot\core\object.cpp:918)
[6] Variant::call_ptr (D:\Godot Engine\godot\core\variant_call.cpp:1229)
[7] GDScriptFunction::call (D:\Godot Engine\godot\modules\gdscript\gdscript_function.cpp:1053)
[8] GDScriptInstance::call (D:\Godot Engine\godot\modules\gdscript\gdscript.cpp:1202)
[9] Object::call (D:\Godot Engine\godot\core\object.cpp:899)
[10] Object::emit_signal (D:\Godot Engine\godot\core\object.cpp:1230)
[11] Object::emit_signal (D:\Godot Engine\godot\core\object.cpp:1286)
[12] FileDialog::_action_pressed (D:\Godot Engine\godot\scene\gui\file_dialog.cpp:209)
[13] FileDialog::_tree_item_activated (D:\Godot Engine\godot\scene\gui\file_dialog.cpp:386)
[14] MethodBind0<FileDialog>::call (D:\Godot Engine\godot\core\method_bind.gen.inc:148)
[15] Object::call (D:\Godot Engine\godot\core\object.cpp:918)
[16] Object::emit_signal (D:\Godot Engine\godot\core\object.cpp:1230)
[17] Object::emit_signal (D:\Godot Engine\godot\core\object.cpp:1286)
[18] Tree::_gui_input (D:\Godot Engine\godot\scene\gui\tree.cpp:2635)
[19] MethodBind1<Tree,Ref<InputEvent> >::call (D:\Godot Engine\godot\core\method_bind.gen.inc:849)
[20] Object::call_multilevel (D:\Godot Engine\godot\core\object.cpp:766)
[21] Object::call_multilevel (D:\Godot Engine\godot\core\object.cpp:864)
[22] Viewport::_gui_call_input (D:\Godot Engine\godot\scene\main\viewport.cpp:1659)
[23] Viewport::_gui_input_event (D:\Godot Engine\godot\scene\main\viewport.cpp:1978)
[24] Viewport::input (D:\Godot Engine\godot\scene\main\viewport.cpp:2874)
[25] Viewport::_vp_input (D:\Godot Engine\godot\scene\main\viewport.cpp:1425)
[26] MethodBind1<Viewport,Ref<InputEvent> const &>::call (D:\Godot Engine\godot\core\method_bind.gen.inc:849)
[27] Object::call (D:\Godot Engine\godot\core\object.cpp:918)
[28] Object::call (D:\Godot Engine\godot\core\object.cpp:848)
[29] SceneTree::call_group_flags (D:\Godot Engine\godot\scene\main\scene_tree.cpp:304)
[30] SceneTree::input_event (D:\Godot Engine\godot\scene\main\scene_tree.cpp:463)
[31] InputDefault::_parse_input_event_impl (D:\Godot Engine\godot\main\input_default.cpp:492)
[32] InputDefault::flush_buffered_events (D:\Godot Engine\godot\main\input_default.cpp:719)
[33] OS_Windows::run (D:\Godot Engine\godot\platform\windows\os_windows.cpp:3544)
[34] widechar_main (D:\Godot Engine\godot\platform\windows\godot_windows.cpp:176)
[35] _main (D:\Godot Engine\godot\platform\windows\godot_windows.cpp:200)
[36] main (D:\Godot Engine\godot\platform\windows\godot_windows.cpp:210)
[37] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[38] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

I thought initially that the `[38] <couldn't map PC to fn name>` was something about me using the `user://` path, which is why I used the `ProjectSettings.globalize_path` function, but even when I changed it to that, it still crashed.

**Comment by drwhut** [comment]
Hmm... I can see you've compiled the right version of Godot for this module, but have you compiled it with the `tools=no` flag at all? I recognise the first line of the backtrace from when I had to patch the engine for release builds.

If you did pass the `tools=no` flag, or if by some other way you're not including the editor in your build, then you'll need to look at [this commit](https://github.com/drwhut/godot/commit/588e961e223706265a2fa6e732f0056958b72b02) in my custom fork to see how to patch the engine so that it doesn't crash when running this module in release mode.

You can also just use [my custom branch](https://github.com/drwhut/godot/tree/tabletop-3.5.3) if you wish, which has these patches included.

**Comment by SlimyFrog123** [comment]
I compiled with the `tools=yes` flag, so I'm not sure why that would be happening. I will try using your custom branch and see if that works! 🤞

**Comment by SlimyFrog123** [comment]
I compiled your fork of the engine, and added the module into the empty folder (I didn't realize that I needed to do that, so it didn't work the first time). It works perfectly fine now!

I'm still not sure why it wasn't working for me. Would using the `target=release_debug` flag cause that issue? That's the only other flag there was when I compiled it. `platform=windows tools=yes target=release_debug`

Thank you for the assistance!

**Comment by drwhut** [comment]
No, `target=release_debug` should work perfectly fine. The command I use to compile the editor on my end is: `scons platform=x11 target=release_debug`

From what I can tell, that commit that I linked on the custom branch should be the only one that affects this. The only thing that I can think of that's happening is that at some point, the way the editor launches new instances when you press "Run" has changed, that is, when you run the game inside the editor, the instance that launches doesn't have the EditorNode in memory (which would make sense, at that instance doesn't need it). Therefore, that would cause the crash you've got since the singleton would be `nullptr`.

At least, that's my theory anyway. Due to the nature of this module, unfortunately I never really intended for it to be used on its own without the patches to the engine itself, so if you want to include the module's import functionality, you need to include the patches, whether that's by adding them manually (based on the commit), or by using my branch, which is guaranteed to work as I test them thoroughly for release builds of Tabletop Club.

Hope this helps!

**Comment by dkodnik** [comment]
Why did need to import assets at all? Why not use the "assets" directory in the directory of the game itself (where is the file being launched)?

**Comment by SlimyFrog123** [comment]
I am making an open-world, multiplayer survival game. The way I have my weapons set up, I have to spend ~30 minutes or so setting up a weapon.

A typical weapon configuration looks like this:
```
{
	"id": "m4a1",
	"display_name": "M4A1",
	"description": "5.56×45mm NATO assault rifle developed in the United States during the 1980s. Shortened version of the M16A2 assault rifle.",
	"max_stack_size": 1,
	"stackable": false,
	"ground_lifetime": 28800,
	"type": "weapon",
	"slot_types": [
		"weapon"
	],
	"ammo_type": "ammo_556x45",
	"rate_of_fire": 0.073,
	"automatic": true,
	"can_aim": true,
	"aim_fov": 80,
	"aim_speed": 10,
	"model_id": "m4a1",
	"x_recoil": 1.3,
	"x_recoil_max": 13,
	"z_recoil": 0,
	"z_recoil_max": -0.12,
	"positions": {
		"aiming": "Vector3( 0.594, -0.426, -1.093 )",
		"aiming_down_sights": "Vector3( 0, -0.335, -0.9 )",
		"up": "Vector3( 0.815, -0.323, -1.189 )",
		"down": "Vector3( 0.357, -0.714, -0.923 )"
	},
	"rotations": {
		"aiming": "Vector3( 0, 90, 0 )",
		"aiming_down_sights": "Vector3( 0, 90, 0.6 )",
		"up": "Vector3( 0, 76.7, 41.141 )",
		"down": "Vector3( -7.583, 141.894, -20.315 )"
	},
	"health_damage": 30.5,
	"shock_damage": 30.5,
	"projectile_speed": 765,
	"gunshot_sound": "m4a1_shot",
	"crosshair": "m4a1",
	"max_distance": 2500
}
```

I'd rather not type all of that out! 😁

So I am making a separate program that will allow me to create weapons more easily, and generate the configuration file as well, so I don't have to spend nearly as much time doing something like copying over vectors.

In this program, I have the user select a model (hence why I need to import the model) and it instances it. Then, they can configure the scale, rotations, positions, etc.

I am also planning to have custom items (item icons, I mean, I already have the functionality for custom items per server) and models per server, which will be broken into chunks of bytes, sent to the client, then re-assembled, imported, and used in the game! All without the client/end-user having to put in any effort, such as downloading and installing a mod or something!

(Edit: I didn't mean to close as not planned. It was a misclick, lol.)

**Comment by drwhut** [comment]
> Why did need to import assets at all? Why not use the "assets" directory in the directory of the game itself (where is the file being launched)?

Out of the box, Godot only exposes a couple of functions to import assets at runtime: you can load in PNGs... and thats it mostly. But for Tabletop Club, I wanted modders to be able to import all sorts of assets, without needing to use the Godot Engine to make another .pck file.

See this proposal for more information: <https://github.com/godotengine/godot-proposals/issues/1632>

**Comment by dkodnik** [comment]
> See this proposal for more information: [godotengine/godot-proposals#1632](https://github.com/godotengine/godot-proposals/issues/1632)

I understand that in 4.2+ this problem (with imports) is mostly solved?

**Comment by drwhut** [comment]
> I understand that in 4.2+ this problem (with imports) is mostly solved?

For the most part yes, looking at [the documentation](https://docs.godotengine.org/en/stable/tutorials/io/runtime_file_loading_and_saving.html) vanilla Godot now comes with a lot of importing functions in GDScript as of 4.3!

- It's now possible to load pretty much any image type at runtime.
- Officially, only OGG Vorbis can be loaded at runtime for audio, but it's possible to load MP3 data manually into a stream. WAV is dead by the wayside however.
- For models, there's a ton of features for glTF files at runtime, but OBJ and DAE file loading is nowhere to be seen yet. Although, I'd imagine making an OBJ loader shouldn't be *too* difficult...
